USE [master]
GO
/****** Object:  Database [Assignment2C2P]    Script Date: 25/02/2019 11:21:23 AM ******/
CREATE DATABASE [Assignment2C2P]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Assignment2C2P', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Assignment2C2P.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Assignment2C2P_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Assignment2C2P_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Assignment2C2P] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Assignment2C2P].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Assignment2C2P] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Assignment2C2P] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Assignment2C2P] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Assignment2C2P] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Assignment2C2P] SET ARITHABORT OFF 
GO
ALTER DATABASE [Assignment2C2P] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Assignment2C2P] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Assignment2C2P] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Assignment2C2P] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Assignment2C2P] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Assignment2C2P] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Assignment2C2P] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Assignment2C2P] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Assignment2C2P] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Assignment2C2P] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Assignment2C2P] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Assignment2C2P] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Assignment2C2P] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Assignment2C2P] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Assignment2C2P] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Assignment2C2P] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Assignment2C2P] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Assignment2C2P] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Assignment2C2P] SET  MULTI_USER 
GO
ALTER DATABASE [Assignment2C2P] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Assignment2C2P] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Assignment2C2P] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Assignment2C2P] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Assignment2C2P] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Assignment2C2P]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 25/02/2019 12:57:23 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[CustomerID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](30) NOT NULL,
	[Email] [varchar](25) NOT NULL,
	[MobileNo] [varchar](10) NOT NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_Email] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Transaction]    Script Date: 25/02/2019 12:57:23 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transaction](
	[TransactionID] [int] IDENTITY(1,1) NOT NULL,
	[TransactionDate] [datetime] NOT NULL,
	[Amount] [money] NOT NULL,
	[CurrencyCode] [char](3) NOT NULL,
	[Status] [varchar](8) NOT NULL,
	[CustomerID] [int] NOT NULL,
 CONSTRAINT [PK_Transaction] PRIMARY KEY CLUSTERED 
(
	[TransactionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Transaction] ADD  CONSTRAINT [DF_Transaction_TransactionDate]  DEFAULT (getdate()) FOR [TransactionDate]
GO
ALTER TABLE [dbo].[Transaction] ADD  CONSTRAINT [DF_Transaction_Amount]  DEFAULT ((0)) FOR [Amount]
GO
ALTER TABLE [dbo].[Transaction]  WITH CHECK ADD  CONSTRAINT [FK_Transaction_Customer] FOREIGN KEY([CustomerID])
REFERENCES [dbo].[Customer] ([CustomerID])
GO
ALTER TABLE [dbo].[Transaction] CHECK CONSTRAINT [FK_Transaction_Customer]
GO
USE [master]
GO
ALTER DATABASE [Assignment2C2P] SET  READ_WRITE 
GO
